### ISSUE TITLE
update OpenAL-Soft to 1.16.0

### ISSUE THREAD

**Issue by FyiurAmron** [LWJGL/lwjgl#117]
Since 1.16.0 has been around for about a year already (http://kcat.strangesoft.net/openal-releases/), I think it can be considered pretty stable. Is there a chance of updating the 1.15.1 DLLs to the newest ones? (I've also filed this on LWJGL/lwjgl#117, yet the DLLs can be updated out-of-the-box without any LWJGL hassle by just renaming the 32/64-bit binaries got from the official http://kcat.strangesoft.net/openal-soft-1.16.0-bin.zip link)

note: you may try latest "nightlies" from http://repo.or.cz/w/openal-soft.git/ if you're feeling adventurous; they patch quite a lot of things vs 1.16.0; I think that (well, if preceded with some testing with some reference libGDX apps) using those shouldn't bring more trouble with OpenAL than we already have. Anyway, I have a hunch that 1.16.1 or 1.17 ain't that far away anyway.

**Comment by Spasi** [comment]
There are no plans to do a 2.9.4 release at the moment. Porting your code to LWJGL 3 is highly recommended.

If this is not an option, do download [LWJGL 3](http://www.lwjgl.org/download), it comes with fresh OpenAL Soft binaries. They're up-to-date with the latest changes (see our [CI account](https://github.com/LWJGL-CI/openal-soft)).
