### ISSUE TITLE
GL.createCapabilities Core OpenGL functions not found on Mac (b55 nightly)

### ISSUE THREAD

**Issue by phr00t** [LWJGL/lwjgl#131]
Thank you for the library fix in b55. However, after pushing the (beta) update to my users, they now get this on Macs:

http://pastebin.com/9shBRupq

Seems to (still) work fine on Windows. No report on Linux yet. The "default" branch using LWJGL 3b49 seems to work fine on Macs...

**Comment by Spasi** [comment]
Thanks, fixed with https://github.com/LWJGL/lwjgl3/commit/9f74b2ddc8baa9d28fece9922f528cc1c789294d.
