### ISSUE TITLE
org.lwjgl.util.NoChecks and glTexSubImage2D

### ISSUE THREAD

**Issue by basil-underscore** [LWJGL/lwjgl#134]
maybe I'm mixing it up but it may be worth changing.

`GL11.glTexSubImage2D` demands a `pixels_buffer_offset` which is not necessarlly an offset.

it is possible to simply feed a host-pointer and trigger a copy. this does not require a `GL_PIXEL_UNPACK_BUFFER` to be bound by `GL15.glBindBuffer`.

texsubimage then does a `GLChecks.ensureUnpackPBOenabled` check which ends in a exception. 

https://www.opengl.org/sdk/docs/man/html/glTexSubImage2D.xhtml states that `pixels` argument is an offset into the currently bound `GL_PIXEL_UNPACK_BUFFER` but also that it is a plain pointer to the image data in memory.

this is of course affecting 1D, 3D, `EXT_direct_state_access` and `ARB_direct_state_access` texuter-methods too.

**Comment by Spasi** [comment]
There are 5 `glTexSubImage2D` overloads that map the `pixels` argument to NIO buffer types. These overloads treat `pixels` as a pointer and not as an offset (and require that `GLChecks.ensureUnpackPBOdisabled` passes). What use-case do you have that requires passing a raw pointer address?

Btw, LWJGL 3 supports this with the "unsafe" method overloads (`nglTexSubImage2D` in this case).

**Comment by basil-underscore** [comment]
That would be a workaround. Thank you.

The use-case is straight forward : not using NIO buffers but working primarily with unsafe alloc/free pointers.

It's easy to convert a pointer to a bytebuffer and use a method without the PBOenabled check. o/
