### ISSUE TITLE
WindowsDisplay and LinuxDisplay not resetting resizable when destroyed

### ISSUE THREAD

**Issue by Marcono1234** [LWJGL/lwjgl#142]
Toggling fullscreen on and off disables window resizing.
Additionally calling `setResizable(true)` does not enable it again because `WindowsDisplay` and `LinuxDisplay` both still have their `resizable` attribut set to `true` because it was not reset when the window was destroyed.
If it was correctly reset, disabling fullscreen would probably set resizable to `true` again on its own if it was previously set, which is very likely the expected behavior.

Based on [MC-68754](https://bugs.mojang.com/browse/MC-68754), reason explained in [MC-111254](https://bugs.mojang.com/browse/MC-111254)

**Comment by Spasi** [comment]
Thank you, this was indeed a bug in the Windows implementation. The Linux implementation is different and not affected.

**Comment by no-identd** [comment]
Unfortunately the Nightlies at http://ci.newdawnsoftware.com/job/LWJGL-git-dist/ haven't gotten updated to include the fix @Spasi commited. :(
