### ISSUE TITLE
Creating LinuxDisplay window does not correctly enable resizing

### ISSUE THREAD

**Issue by Marcono1234** [LWJGL/lwjgl#143]
This is a theoretical report because I don't have a Linux system to test.

It is very likely that a `LinuxDisplay` window which was resizable before but then destroyed is not displayed as resizable when it is created again, besides its `resizable` attribut being `true`. The reason for this is that the method [`createWindow`](https://github.com/LWJGL/lwjgl/blob/master/src/java/org/lwjgl/opengl/LinuxDisplay.java#L454) is only setting the value for the attribut instead of calling `setResizable(boolean)`.

Reproducing this bug is probably blocked by #142

**Comment by Spasi** [comment]
I haven't had time to test this yet, but the implementation looks fine. The cached resizable state is overridden on window creation and the correct value is passed to native code.

**Comment by Marcono1234** [comment]
Oh yes, you are right. I thought it would call `setResizable(boolean)` but did not see that the value is passed to the native code. Sorry.
