### ISSUE TITLE
[Windows] OpenGL (from integrated Intel Graphics) not being recognized after Windows 10's (x86) Creators Update

### ISSUE THREAD

**Issue by GlitchyPSIX** [LWJGL/lwjgl#146]
The application that I'm trying to run used to work perfectly in Windows 10 before the Creators Update (v1703).

Before updaing Java to the latest version, the application loaded and rendered until a certain point, where the following popped up:

```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x782721f4, pid=10048, tid=6820
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b26) (build 1.8.0_40-b26)
# Java VM: Java HotSpot(TM) Client VM (25.40-b25 mixed mode windows-x86 )
# Problematic frame:
# C  [msvcr100.dll+0x121f4]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

After updating Java to the latest version ( `java version "1.8.0_131"` ), the application does not even render, and this pops up instead:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 1.1.0
Type: OpenGL
Version: 1:1:0
Vendor: Microsoft Corporation
Renderer: GDI Generic
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:347)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGL(LwjglGraphics.java:226)
        at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:217)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:144)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

Even though, GLview reports my graphics card as OGL 2.1-compatible.
https://i.imgur.com/LcPiX5y.png
Any help?

**Comment by Spasi** [comment]
Sounds like #119. There are two workarounds available, a [safe that needs work](https://github.com/LWJGL/lwjgl/issues/119#issuecomment-173983180) and a [risky but simple](https://github.com/LWJGL/lwjgl/issues/119#issuecomment-264291065).

**Comment by GlitchyPSIX** [comment]
Changing ``java.exe``'s manifest via Resource Hacker doesn't seem to work, and I'm kinda afraid that my graphics drivers aren't compatible with that patch.

**Comment by Spasi** [comment]
> Changing java.exe's manifest via Resource Hacker doesn't seem to work

Could you please verify by running the application with Java 8u25? If it runs, then something went wrong with the manifest modification.

**Comment by GlitchyPSIX** [comment]
Runs before a certain time where I reported in previous versions that it crashed with a problematic frame on MSVCR100.dll.

**Comment by GlitchyPSIX** [comment]
Alright, the MSVCR100.dll problem is caused by GodMode being in the Desktop, so I guess that doesn't come to the case
For some odd reason, the problem is fixed.
Thanks for your help!
