### ISSUE TITLE
Key-Locking Behaviour (keysym/keycode-error on keyrelease)

### ISSUE THREAD

**Issue by Drezil** [LWJGL/lwjgl#28]
redirected from: https://mojang.atlassian.net/browse/MC-15142

Minecraft uses KeySym under linux to determine which key was pressed. KeySym by definition only has its value set correctly at keyPRESS - not keyRELEASE.
To get the real values use the KeyCode.
e.g. having de_de set as default layout yields (in xev):
> KeyPress event, serial 40, synthetic NO, window 0x4600001,
> root 0xa9, subw 0x0, time 1668220, (670,378), root:(672,401),
> state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
> XLookupString gives 0 bytes: 
> XmbLookupString gives 0 bytes: 
> XFilterEvent returns: False
> KeyRelease event, serial 40, synthetic NO, window 0x4600001,
> root 0xa9, subw 0x0, time 1668345, (616,314), root:(618,337),
> state 0x1, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
> XLookupString gives 0 bytes: 
> XFilterEvent returns: False

but with de_neo you get:

> KeyPress event, serial 40, synthetic NO, window 0x4600001,
> root 0xa9, subw 0x0, time 1722888, (608,465), root:(610,488),
> state 0x2000, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
> XLookupString gives 0 bytes: 
> XmbLookupString gives 0 bytes: 
> XFilterEvent returns: False
> KeyRelease event, serial 40, synthetic NO, window 0x4600001,
> root 0xa9, subw 0x0, time 1723003, (608,465), root:(610,488),
> state 0x2001, keycode 50 (keysym 0xffe5, Caps_Lock), same_screen YES,
> XKeysymToKeycode returns keycode: 66
> XLookupString gives 0 bytes: 
> XFilterEvent returns: False

(This Effect is a side-effect on having both shift-keys (pressed at the same time) act as Caps-Lock - but thats just a guess).
A similar bug was reported to another application ( https://bugzilla.gnome.org/show_bug.cgi?id=683534#c7 ).
Workaround:
If you make de_de the default keyboard-layout and just switch to de_neo, minecraft uses the de_de-Keysym (in every menu - so you have wasd "set" for walking), but you still have neo in text-chat (thus having vuia as the keys you actually press for walking).
Doing so, however, disables the Mod4-Switch making 2 of the 6 levels of the neo-layout (see http://www.neo-layout.org for reference) unusable.
This will affect other layouts where similar behaviour is enforced, too.

Edit: To make the Mod4-Switch (at least AltGr) workable again i could add an override ("Key to choose 5th level" set to "Right Alt chooses 5th level, locks when pressed together with another 5th-level-chooser") in the keyboard settings under KDE. YMMV.

**Comment by florianjacob** [comment]
This is still a problem with Minecraft 1.8.3 which seems to use LWJGL 1.9.4-nightly.

**Comment by Spasi** [comment]
The mapEventToKeySym code was written in 2006 by a developer that does not contribute to LWJGL anymore. I'm not familiar with Linux keyboard handling, but I will gladly accept a fix from someone that knows what they're doing.

Maybe @wmbr could help? Have you tested the 1 -> 0 fix to make sure it doesn't break anything else?

**Comment by florianjacob** [comment]
Tried to understand what's going on there and prove the theory that the "1" adds some kind of additional, unnecessary shift key press. It results in a call to XLookupKeysym, from the man page:

       The XLookupKeysym function uses a given keyboard event and the index you specified to return the KeySym from the list that corre‐
       sponds to the KeyCode member in the XKeyPressedEvent or XKeyReleasedEvent structure.  If no KeySym is defined for the KeyCode of
       the event, XLookupKeysym returns NoSymbol.

But what are the possible values for this index? The best candidate I found was in /usr/include/X11/extensions/XKB.h:

```
    /*
     * Group Index and Mask:
     *  - Indices into the kt_index array of a key type.
     *  - Mask specifies types to be changed for XkbChangeTypesOfKey
     */
#define	XkbGroup1Index		0
#define	XkbGroup2Index		1
#define	XkbGroup3Index		2
#define	XkbGroup4Index		3
#define	XkbAnyGroup		254
#define	XkbAllGroups		255
```

If I am right, this means that group=1 corresponds to XkbGroup3Index (as it's later multiplied by 2 in the getKeySym function) which would be the AltGr key, and index=1 corresponds to XkbGroup2Index, the shift key.

But I'm really not sure whether this is the way this code is intended to work.

**Comment by wmbr** [comment]
@Spasi I've patched my version for a year now and it's working but I can't speak for other machines/keyboards and I haven't fully understood the code.

**Comment by Spasi** [comment]
So, I did some testing with de_neo (on OpenSUSE 13.2, KDE 4) and was able to reproduce the issue and verify that the change @wmbr suggested resolves it. The above commit also simplified the code considerably.

Just a note on the Mod4 switch, in case it affects other people. If I use the KDE layout indicator to switch to de_neo, the Mod4 switch does not work, i.e. you can't access layers 4 and 6. But if I run:

`setxkbmap -layout de -variant neo`

Mod4 works as expected. The shift bug is gone and all layers work fine in LWJGL.

**Comment by exothermal** [comment]
Hello!

 

New message, please read <http://kittyshine.com/impossible.php?hsiva>

 

arne@exothermal.de

**Comment by exothermal** [comment]
Hey!

 

New message, please read <http://profi2w.com.br/fit.php?zlft>

 

arne@exothermal.de

**Comment by exothermal** [comment]
Hey!

 

New message, please read <http://www.vmginternational.com/sleep.php?00>

 

arne@exothermal.de

**Comment by exothermal** [comment]
Hey!

 

New message, please read <http://spanishliveus.com/might.php?idljd>

 

arne@exothermal.de

**Comment by exothermal** [comment]
Hey!

 

New message, please read <http://gombong-tour.com/care.php?j3d>

 

arne@exothermal.de

**Comment by Severus157** [comment]
Hello.
I just found this post here after a week of trying to get a hold of this error... Could someone explain how to fix it for non-java programmers? Please... What is needed to change to play Minecraft?
