### ISSUE TITLE
Quitting Java application resets refresh rate

### ISSUE THREAD

**Issue by amasondev** [LWJGL/lwjgl#64]
Upon quitting the LWJGL application, desktop refresh rate is forced to 60Hz. I can confirm this as a LWJGL issue because it occurs in both Minecraft and LibGDX desktop builds. I have only tested this with an NVIDIA card, but it occurs in both Windows 7 64bit and Linux based  64bit OSes using proprietary NVIDIA drivers.

A bug report was filed with mojang here: https://bugs.mojang.com/browse/MC-36746

**Comment by ali1234** [comment]
This is still happening for me, with 2.9.4-nightly-20150209 supplied by Minecraft. Interestingly older versions do not do it, so I would guess that the "fix" for this caused a regression.

xrandr before:

`
Screen 0: minimum 8 x 8, current 1920 x 1200, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95*+  59.88  
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-1 disconnected (normal left inverted right x axis y axis)
`

xrandr after:

`
Screen 0: minimum 8 x 8, current 1920 x 1200, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 disconnected (normal left inverted right x axis y axis)
DP-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95 +  59.88* 
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
`

Notice that both modes are extremely close to 60Hz. However 59.88Hz does not work correctly on my monitor and gets rendered as 960x1200.

**Comment by ali1234** [comment]
This happens because the refresh rate is stored in an int, and java truncates when converting float to int. So 59.95 and 59.89 both get stored as 59. Then when you restore the refresh at exit, 59 is deemed closer to 59.88, so it incorrectly picks that mode.

**Comment by ali1234** [comment]
Since lwjgl calls out to xrandr binary in order to change the refresh rate you can work around this problem by providing a fake xrandr which does nothing ahead of the real executable in your path.

**Comment by ali1234** [comment]
```
#!/bin/bash

# This will loop through all command line arguments.
# If it finds "--rate" then it looks at the next argument.
# If the next argument is "59" it is changed to "59.95"
# Then xrandr is run with the modified arguments.

options=()  # the buffer array for the parameters

while [[ $1 ]]
do
    case "$1" in
        --rate)
            options+=("$1")
            shift
            case "$1" in
                59)
                    options+=("59.95")
                    shift
                    ;;
                *)
                    options+=("$1")
                    shift
                    ;;
            esac
            ;;
        *)
            options+=("$1")
            shift
            ;;
    esac
done

exec /usr/bin/xrandr "${options[@]}"
```

**Comment by tfg13** [comment]
Original hotfix guy here, I just posted to the forums to explain the situation: http://forum.lwjgl.org/index.php?topic=6047.0

**Comment by no-identd** [comment]
Unfortunately the Nightlies at http://ci.newdawnsoftware.com/job/LWJGL-git-dist/ haven't gotten updated to include the fix @Spasi commited. :(
