### ISSUE TITLE
Display.setDisplayMode() crashes to desktop after parent Canvas is resized.

### ISSUE THREAD

**Issue by fragmer** [LWJGL/lwjgl#98]
Steps to reproduce
----
I discovered a crash-to-desktop that happens when the following conditions are met:
- User is running Windows 7, 8, or 8.1
- User is using JRE 7u71, 8u20, 8u25, or 8u45 (does not crash on 7u55 or 7u45). Other Java versions may or may not be affected -- I was only able to test these six.
- A Display is created, with setResizable(true) and Canvas as a parent.
- The window is resized by dragging a corner. Maximizing the window does not cause a crash, but restoring window from maximized does.
- <code>Display.setDisplayMode(...)</code> is called to adjust the OpenGL context size to match the resized Canvas.

Crash description
----
Crash happens immediately after <code>Display.setDisplayMode(...)</code> is invoked. Windows shows "unhandled win32 exception in java.exe" dialog.

Attempting to debug the process in VisualStudio produces a more detailed message:
<code>Unhandled exception at 0x0000000300000002 in java.exe: 0xC000041D: An unhandled exception was encountered during a user callback.</code>
I also obtained a stack trace: https://gist.github.com/fragmer/23ce6520953c50ffdb11/

Test case
----
I've simplified the crash conditions down to this test case: https://gist.github.com/fragmer/00bcc74756a675f273cd

For testing convenience, here is an archive with the test case source code, compiled jar, and copies of LWJGL that I'm using: http://matvei.org/temp/ResizeCrashTest.zip

On affected platforms (JRE 7u71, 8u20, 8u25, 8u45) an 800×600 window will show up, and crash when resized: http://matvei.org/temp/2014-10-26_16-09-49.mp4

On non-affected platforms (JRE 7u55 or 7u45) the same window will resize without problems: http://fi.hypertext.ml/32-10_26_14-14-24.mp4

**Comment by fragmer** [comment]
Still reproducible with LWJGL 2.9.2 and 2.9.3 on all affected platforms.

**Comment by Spasi** [comment]
Hey Matvei,

Sorry for not looking into this earlier, somehow I completely missed it.

I have fixed the crash by ignoring calls to setDisplayMode when the Display parent is set. You do not need to call it at all, when the Canvas parent is resized, the Display is also resized automatically.

Thank you for reporting this issue and the very detailed information you provided.

**Comment by fragmer** [comment]
Thank you very much for fixing this, Spasi!

It does look like we were misusing setDisplayMode(), since Display already detects size changes in its parent component. Just today we've refactored the code to avoid extra setDisplayMode(...) calls. Thanks for the tip!
